os: osx
language: cpp
compiler: clang

before_install:
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update          ; fi

script:
    - echo "TRAVIS_OS_NAME=$TRAVIS_OS_NAME"
    - env
    - git clone https://github.com/ARM-software/progress64 && cd progress64 && make all && cd ..
    - ./autogen.sh && ./configure --disable-numa --with-progress64=$PWD/progress64
    - make
